theme: jekyll-theme-hacker
title: ICSSecurity.io

description: A blog about ICS Cyber Security
author:
  name: David Kennedy
  url: https://icssecurity.io

baseurl: /blog

paginate: 3
owner: admin
year: 2022
